core/urls.py
from debug_toolbar.toolbar import debug_toolbar_urls
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path("admin/", admin.site.urls),
    path("", include("messanger.urls")),
    path("nested-forms/", include("nested_forms.urls")),
    path("accounts/", include("accounts.urls")),
] + debug_toolbar_urls()

nested_forms/urls.py
from django.urls import path

from nested_forms.views import (ParentCreateView, ParentListView,
                                ParentUpdateView)

app_name = "nested_forms"

urlpatterns = [
    path("parents/", ParentListView.as_view(), name="parent-list"),
    path("parents/create/", ParentCreateView.as_view(), name="parent-create"),
    path("parents/<int:pk>/update/", ParentUpdateView.as_view(), name="parent-update"),
]

nested_forms/models.py
from django.db import models


class Parent(models.Model):
    name = models.CharField(max_length=250)

    def __str__(self):
        return self.name


class Child(models.Model):
    name = models.CharField(max_length=250)
    parent = models.ForeignKey(Parent, on_delete=models.CASCADE, related_name="children")

    class Meta:
        verbose_name_plural = "Children"

    def __str__(self):
        return self.name

nested_forms/forms.py
from django.forms.models import inlineformset_factory

from nested_forms.models import Child, Parent

ChildFormset = inlineformset_factory(
    Parent, Child, fields=('name',), extra=1
)


# -------------------------------------adding class to form fields---------------------------------------------------
# class MyForm(forms.Form):
#     myfield = forms.CharField(widget=forms.TextInput(attrs={'class': 'myfieldclass'}))
# or
# class MyForm(forms.Form):
#     myfield = forms.CharField(widget=forms.TextInput(attrs={'class': 'myfieldclass'}))
# or
# class MyForm(forms.ModelForm):
#     class Meta:
#         model = MyModel
#         widgets = {
#             'myfield': forms.TextInput(attrs={'class': 'myfieldclass'}),
#         }

nested_forms/views.py
from django.db import transaction
from django.http import HttpResponseRedirect
from django.urls import reverse_lazy
from django.views import generic
from django.views.generic.list import ListView

from nested_forms.forms import ChildFormset
from nested_forms.models import Parent


class ParentListView(ListView):
    model = Parent

    def get_queryset(self):
        return Parent.objects.prefetch_related("children")


class ParentCreateView(generic.CreateView):
    model = Parent
    fields = ["name"]
    success_url = reverse_lazy("nested_forms:parent-list")
    template_name = "nested_forms/parent_form_js.html"

    def get_context_data(self, **kwargs):
        data = super().get_context_data(**kwargs)
        data["children_form"] = ChildFormset(self.request.POST or None)

        return data

    def form_valid(self, form):
        context = self.get_context_data()
        children_form = context["children_form"]

        with transaction.atomic():
            self.object = form.save() # create parent

            if children_form.is_valid():
                children_form.instance = self.object
                children_form.save()

        return HttpResponseRedirect(self.get_success_url())


class ParentUpdateView(generic.UpdateView):
    model = Parent
    fields = ["name"]
    success_url = reverse_lazy("nested_forms:parent-list")
    template_name = "nested_forms/parent_form_js.html"

    def get_context_data(self, **kwargs):
        data = super().get_context_data(**kwargs)
        data["children_form"] = ChildFormset(self.request.POST or None, instance=self.object)

        return data

    def form_valid(self, form):
        context = self.get_context_data()
        children_form = context["children_form"]

        with transaction.atomic():
            self.object = form.save()

            if children_form.is_valid():
                children_form.instance = self.object
                children_form.save()

        return HttpResponseRedirect(self.get_success_url())

templates/nested_forms/parent_form.html
{% extends "base.html" %}
{% load crispy_forms_filters %}

{% block content %}
<h1>Parents</h1>
<form method="post">
  {% csrf_token %}
  {{ form|crispy }}
  <h2>Children</h2>
  {{ children_form|crispy }}
  <input type="submit" value="Save">
</form>
{% endblock %}

templates/nested_forms/parent_form_js.html
{% extends "base.html" %}
{% load static %}
{% load crispy_forms_filters %}

{% block content %}
  <h1>Parents</h1>
  <div class="col-md-4">
    <form action="" method="post">
      {% csrf_token %}
      {{ form.as_p }}

      <table class="table">
        {{ children_form.management_form }}

        {% for form in children_form.forms %}
          {% if forloop.first %}
            <thead>
            <tr>
              {% for field in form.visible_fields %}
                <th>{{ field.label|capfirst }}</th>
              {% endfor %}
            </tr>
            </thead>
          {% endif %}
          <tr class="{% cycle 'row1' 'row2' %} formset_row">
            {% for field in form.visible_fields %}
              <td>
                {% if forloop.first %}
                  {% for hidden in form.hidden_fields %}
                    {{ hidden }}
                  {% endfor %}
                {% endif %}
                {{ field.errors.as_ul }}
                {{ field }}
              </td>
            {% endfor %}
          </tr>
        {% endfor %}
      </table>
      <input type="submit" value="Save"/> <a href="{% url 'nested_forms:parent-list' %}">back to the list</a>
    </form>
  </div>
  <script src="//ajax.googleapis.com/ajax/libs/jquery/2.1.3/jquery.min.js"></script>
  <script src="{% static 'js/formset/jquery.formset.js' %}"></script>
  <script type="text/javascript">
    $('.formset_row').formset({
      addText: 'add child',
      deleteText: 'delete',
      prefix: 'children'
    });
  </script>
{% endblock %}

templates/nested_forms/parent_list.html
{% extends "base.html" %}

{% block content %}
  <h1>Parent List</h1>
  <a href="{% url 'nested_forms:parent-create' %}">new parent</a>
  <br>
  <br>
  <ul class="list-group">
    {% for parent in parent_list %}
      <li class="list-group-item">
        <a href="{% url 'nested_forms:parent-update' parent.pk %}">{{ parent.name }}</a>
        <ul class="list-group">
          {% for child in parent.children.all %}
            <li class="list-group-item">{{ child.name }}</li>
          {% empty %}
            Without children
          {% endfor %}
        </ul>
      </li>
    {% empty %}
      <p>No Parents</p>
    {% endfor %}
  </ul>
{% endblock %}