accounts/urls.py
from django.urls import include, path

from accounts.views import UserDetailView, activate, register

app_name = "accounts"

urlpatterns = [
    path("", include("django.contrib.auth.urls")),
    path("register/", register, name="register"),
    path("activate/<str:uid>/<str:token>/", activate, name="activate"),
    path("users/<int:pk>/", UserDetailView.as_view(), name="user-detail"),
]

core/urls.py
from debug_toolbar.toolbar import debug_toolbar_urls
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path("admin/", admin.site.urls),
    path("", include("messanger.urls")),
    path("nested-forms/", include("nested_forms.urls")),
    path("accounts/", include("accounts.urls")),
] + debug_toolbar_urls()

templates/includes/messages.html
{% if messages %}
    {% for message in messages %}
        {% if message.tags == 'success' %}
            <div class="alert alert-success alert-dismissible" role="alert">
                <a href="#" class="close" data-dismiss="alert" aria-label="close">&times;</a>
                {{ message|safe|escape }}
            </div>
        {% elif message.tags == 'error' %}
            <div class="alert alert-danger alert-dismissible" role="alert">
                <a href="#" class="close" data-dismiss="alert" aria-label="close">&times;</a>
                {{ message|safe|escape }}
            </div>
        {% elif message.tags == 'info' %}
            <div class="alert alert-info alert-dismissible" role="alert">
                <a href="#" class="close" data-dismiss="alert" aria-label="close">&times;</a>
                {{ message|safe|escape }}
            </div>
        {% elif message.tags == 'warning' %}
            <div class="alert alert-warning alert-dismissible" role="alert">
                <a href="#" class="close" data-dismiss="alert" aria-label="close">&times;</a>
                {{ message|safe|escape }}
            </div>
        {% endif %}
    {% endfor %}
{% endif %}

templates/includes/sidebar.html
<ul class="nav bg-info">
  <li class="nav-item">
    <a class="nav-link link-light" href="{% url "home" %}">Home</a>
  </li>
  <li class="nav-item">
    <a class="nav-link link-light" href="{% url "message-list" %}">CHAT</a>
  </li>
  {% if not user.is_authenticated %}
    <li class="nav-item">
      <a class="nav-link link-light" href="{% url "accounts:login" %}">Log In</a>
    </li>
    		<li class="nav-item">
    			<a class="nav-link link-light" href="{% url "accounts:register" %}">Sign Up</a>
    		</li>
  {% else %}
    <li class="nav-item">
      <a class="nav-link link-light" href={% url "accounts:user-detail" user.pk %}>My Profile</a>
    </li>
    <li class="nav-item ms-auto">
      <form action="{% url "accounts:logout" %}" method="post" style="margin: 0; padding: 0;">
        {% csrf_token %}
        <a class="nav-link link-light" href="#" onclick="this.parentNode.submit();">Log Out</a>
      </form>
    </li>
  {% endif %}
</ul>